### ISSUE TITLE
Cancel button when waiting for players

### ISSUE THREAD

**Issue by GodotHosting** [GodotHosting/volleyball-game#4]

**Comment by themehdev** [comment]
yes i agree. I am going to do that but not post it because you said that you were working on networking stuff, and I don't want to accidentally mess that up.

**Comment by themehdev** [comment]
here is the code. (for connecting.gd)
`extends Control

var status = "connecting"

func _ready():
	NetworkManager.start_connecting()
	NetworkManager._client.connect("connection_established", self, "connected")
	NetworkManager.connect("start", self, "start_game")

func connected(_proto):
	status = "waiting"
	$VBoxContainer/Label.text = "Waiting for players..."
	NetworkManager.send_msg({"ready": true})

func start_game():
	get_tree().change_scene("res://Level/Level.tscn")

func _on_Timer_timeout():
	if status == "connecting":
		$VBoxContainer/Label.text += "."
		if $VBoxContainer/Label.text == "Connecting....":
			$VBoxContainer/Label.text = "Connecting"


func _on_Button_pressed():
	get_tree().change_scene("res://Menu Screens/Menu.tscn")
`
for connecting.tscn, because I don't think that will change, I will upload
